#!/bin/bash
if [ $(id -u) -eq 0 ]
then
	echo -e "\033[1;32mNome de Usuário:\033[0;37m"; read -p " " name
	echo -e "\033[1;32mPassword para $name:\033[0;37m"; read -p " " pass
	echo -e "\033[1;32mQuantos dias deve $name durar:\033[0;37m"; read -p " " daysrnf
	echo -e "\033[1;32mLimite de logins simultaneos:\033[0;37m"; read -p " " limiteuser
	echo -e "\033[0m"
	if cat /etc/passwd |grep $name: |grep -vi [a-z]$name |grep -v [0-9]$name > /dev/null
	then
		echo -e "\033[1;31mUsuario $name já existe\033[0m"
	else
		valid=$(date '+%C%y-%m-%d' -d " +$daysrnf days")
		datexp=$(date "+%d/%m/%Y" -d "+ $daysrnf days")
		useradd -M -s /bin/false $name -e $valid
		( echo "$pass";echo "$pass" ) | passwd $name 2> /dev/null
		limite $name $limiteuser
		echo -e "\033[1;36mUsuário: \033[0m$name"
		echo -e "\033[1;36mPasswrod: \033[0m$pass"
		echo -e "\033[1;36mExpira:\033[0m $datexp"
	    echo "$pass" > /etc/VpsPackdir/senha/$name
	fi
else
	if echo $(id) |grep sudo > /dev/null
	then
	echo "O teu usuário está em sudo"
	echo -e "Para executar como root escreva: \033[1;31msudo su\033[0m"
	echo -e "Ou execute criarusuario como sudo. \033[1;31msudo criarusuario\033[0m"
	else
	echo -e "Não está como usuário root, nem com seus acessos (sudo)\nPara executar como root escreve \033[1;31msu\033[0m e escreve a password root"
	fi
fi

