#!/bin/bash
cd
if [ $(id -u) != 0 ]
then
echo "Execute o script como root"
exit
fi
echo -e "\033[1;30mInstalando...\033[0m"
mkdir /etc/VpsPackdir 2>/dev/null
mkdir /etc/VpsPackdir/limite 2>/dev/null
mkdir /etc/VpsPackdir/senha 2>/dev/null
rm -rf /bin/limite 2>/dev/null
wget -o /dev/null -O- https://raw.githubusercontent.com/sauceisgood/vpsmanager/master/limite > /bin/limite
chmod +x /bin/limite
rm -rf /bin/criarusuario 2>/dev/null
wget -o /dev/null -O- https://raw.githubusercontent.com/sauceisgood/vpsmanager/master/criarusuario > /bin/criarusuario
chmod +x /bin/criarusuario
rm -rf /bin/deletarusuario 2>/dev/null
wget -o /dev/null -O- https://raw.githubusercontent.com/sauceisgood/vpsmanager/master/deletarusuario > /bin/deletarusuario
chmod +x /bin/deletarusuario
rm -rf /bin/redefinirusuario 2>/dev/null
wget -o /dev/null -O- https://raw.githubusercontent.com/sauceisgood/vpsmanager/master/redefinirusuario > /bin/redefinirusuario
chmod +x /bin/redefinirusuario
rm -rf /bin/vpspack 2>/dev/null
wget -o /dev/null -O- https://raw.githubusercontent.com/sauceisgood/vpsmanager/master/vpspack > /bin/vpspack
chmod +x /bin/vpspack
rm -rf /bin/speedtest.py 2>/dev/null
wget -o /dev/null -O- https://raw.githubusercontent.com/sauceisgood/vpsmanager/master/speedtest.py > /bin/speedtest.py
chmod +x /bin/speedtest.py
rm -rf /bin/dropbear 2>/dev/null
wget -o /dev/null -O- https://raw.githubusercontent.com/sauceisgood/vpsmanager/master/dropbear > /root/dropbear
chmod +x /root/dropbear
rm -rf /bin/shadowsocks 2>/dev/null
wget -o /dev/null -O- https://raw.githubusercontent.com/sauceisgood/vpsmanager/master/shadowsocks > /bin/shadowsocks
chmod +x /bin/shadowsocks
rm -rf /bin/banner 2>/dev/null
wget -o /dev/null -O- https://raw.githubusercontent.com/sauceisgood/vpsmanager/master/banner > /bin/banner
chmod +x /bin/banner
rm -rf badvpn 2>/dev/null
wget -o /dev/null -O- https://raw.githubusercontent.com/sauceisgood/vpsmanager/master/badvpn > badvpn
chmod +x badvpn
rm -rf /bin/menu_firewall 2>/dev/null
wget -o /dev/null -O- https://raw.githubusercontent.com/sauceisgood/vpsmanager/master/menu_firewall > /bin/menu_firewall
chmod +x /bin/menu_firewall
m -rf /bin/menu_hosts 2>/dev/null
wget -o /dev/null -O- https://raw.githubusercontent.com/sauceisgood/vpsmanager/master/menu_hosts > /bin/menu_hosts
chmod +x /bin/menu_hosts
m -rf /bin/menu_shadowsocks 2>/dev/null
wget -o /dev/null -O- https://raw.githubusercontent.com/sauceisgood/vpsmanager/master/menu_shadowsocks > /bin/menu_shadowsocks
chmod +x /bin/menu_shadowsocks
m -rf /bin/menu_badvpn 2>/dev/null
wget -o /dev/null -O- https://raw.githubusercontent.com/sauceisgood/vpsmanager/master/menu_badvpn > /bin/menu_badvpn
chmod +x /bin/menu_badvpn
m -rf /bin/menu_backup 2>/dev/null
wget -o /dev/null -O- https://raw.githubusercontent.com/sauceisgood/vpsmanager/master/menu_backup > /bin/menu_backup
chmod +x /bin/menu_backup
rm -rf /bin/webmin 2>/dev/null
wget -o /dev/null -O- https://raw.githubusercontent.com/sauceisgood/vpsmanager/master/webmin > /bin/webmin
chmod +x /bin/webmin
wget -o /dev/null -O- https://raw.githubusercontent.com/sauceisgood/vpsmanager/master/stunnel.sh > /bin/stunnel
chmod +x /bin/stunnel
clear
echo -e "\033[1;32mInstalacao concluida\n\033[1;30mExecute:"
echo -e "\n\033[1;32mvpspack \033[1;30mMenu com opcoes"
echo -e "\033[1;32mcriarusuario \033[1;30mCriar usuario com data e limite"
echo -e "\033[1;32mdeletarusuario \033[1;30mDeletar usuario ou apenas desconectar"
echo -e "\033[1;32mredefinirusuario \033[1;30mAlterar data, senha, etc, de um usuario"
echo -e "\033[1;32mlimite \033[1;30mLimite de logins simultaneos\033[0m"
rm -rf install
