#!/bin/bash
echo -e "\033[1;33mShadowsocks\033[1;30m
1) Activar Shadowsocks
2) Parar Shadowsocks"
read -p "opção: " option
if [ $option -eq 1 ]; then
ssserver -c /etc/shadowsocks.json -d start
exit 0
fi

if [ $option -eq 2 ]; then
ssserver -c /etc/shadowsocks.json -d stop
exit
fi

