#!/bin/bash

########## Install Shadowsocks ##########
# <https://github.com/shadowsocks/shadowsocks/blob/master/README.md>

sudo apt-get update
sudo apt-get install python-pip -y
sudo pip install -i https://pypi.python.org/simple/ --upgrade pip
sudo pip install shadowsocks


########## Setup Shadowsocks ##########
# How to generate random string: <https://gist.github.com/earthgecko/3089509>
# And the `tr: Illegal byte sequence` issue:
# <http://unix.stackexchange.com/questions/45404/why-cant-tr-read-from-dev-urandom-on-osx>
ramdom_pass=$(LC_CTYPE=C tr -dc 'a-zA-Z0-9' < /dev/urandom | fold -w 16 | head -n 1)

ss_config="{
  \"server\":\"direccion\",
  \"server_port\":447,
  \"local_address\": \"127.0.0.1\",
  \"local_port\":1080,
  \"password\":\"contra\",
  \"timeout\":300,
  \"method\":\"aes-256-cfb\",
  \"fast_open\": false
}
"

# Remember to add the quotes around the variable otherwise
# you won't see the newline characters.

echo "$ss_config" > /etc/shadowsocks.json


########## Optimizing Shadowsocks ##########
# <https://github.com/shadowsocks/shadowsocks/wiki/Optimizing-Shadowsocks>


cat <<EOT > /etc/sysctl.d/local.conf
# max open files
fs.file-max = 51200
# max read buffer
net.core.rmem_max = 67108864
# max write buffer
net.core.wmem_max = 67108864
# default read buffer
net.core.rmem_default = 65536
# default write buffer
net.core.wmem_default = 65536
# max processor input queue
net.core.netdev_max_backlog = 4096
# max backlog
net.core.somaxconn = 4096

# resist SYN flood attacks
net.ipv4.tcp_syncookies = 1
# reuse timewait sockets when safe
net.ipv4.tcp_tw_reuse = 1
# turn off fast timewait sockets recycling
net.ipv4.tcp_tw_recycle = 0
# short FIN timeout
net.ipv4.tcp_fin_timeout = 30
# short keepalive time
net.ipv4.tcp_keepalive_time = 1200
# outbound port range
net.ipv4.ip_local_port_range = 10000 65000
# max SYN backlog
net.ipv4.tcp_max_syn_backlog = 4096
# max timewait sockets held by system simultaneously
net.ipv4.tcp_max_tw_buckets = 5000
# turn on TCP Fast Open on both client and server side
net.ipv4.tcp_fastopen = 3
# TCP receive buffer
net.ipv4.tcp_rmem = 4096 87380 67108864
# TCP write buffer
net.ipv4.tcp_wmem = 4096 65536 67108864
# turn on path MTU discovery
net.ipv4.tcp_mtu_probing = 1

# for high-latency network
net.ipv4.tcp_congestion_control = hybla

# for low-latency network, use cubic instead
# net.ipv4.tcp_congestion_control = cubic
EOT

sysctl --system

ulimit -n 51200

# Start shadowsocks server at background
# <https://github.com/shadowsocks/shadowsocks/wiki/Configuration-via-Config-File>
ssserver -c /etc/shadowsocks.json -d start

echo
echo -e "Your shadowsocks config file is at: '/etc/shadowsocks.json', and your config is: \n$ss_config"
ssserver -c /etc/shadowsocks.json -d start
cat /etc/shadowsocks.json
echo -e "\033[01;31mTerminado !! \033[0m"
echo -e "\033[01;31mPortas adicionadas: \033[0m"
echo -e "\033[01;31mOpenSSH: 22/443 \033[0m"
echo -e "\033[01;31mSquid: 80/8080/8799/3128 \033[0m"
echo -e "\033[01;31mDropbear: 444 \033[0m"
echo -e "\033[01;31mShadowsocks: 447 \033[0m"
echo -e "\033[01;31mbadVpn: 7300 \033[0m"
netstat -tunlp

