#!/bin/bash
echo "deb https://download.webmin.com/download/repository sarge contrib" >> /etc/apt/sources.list
sudo apt-get install apt-transport-https -y
sudo apt-get update && sudo apt-get upgrade -y -q
cd /root
wget http://www.webmin.com/jcameron-key.asc
apt-key add jcameron-key.asc
apt-get update
rm -r jcameron-key.asc
apt-get install webmin -y
cd
echo Webmin instalado !!!
